services:
  java_app:
    container_name: java_app
    image: bike-java-app:1.0.0
    build: .
    ports:
      - 9090:9090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:16.8
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.0
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data_springBoot:/opt/keycloak/data
    depends_on:
      - java_db

volumes:
  keycloak_data_springBoot:
    external: true

